---
- hosts: localhost
  tasks:
    - name: Create incident
      servicenow.itsm.incident:
        state: new
        caller: abel.tuter
        short_description: this was created by Ansible
        description: "Did you know that {{ ansible_date_time.date }}"
        impact: low
        urgency: low
